language: node_js

node_js:
    - 'node'
 
 install:
  - npm install
script:
  - npm run build
 
 after_script:
  - cd ./dist
  - git init
  - git config user.name "${USER_NAME}"
  - git config user.email "${USER_EMAIL}"
  - git add .
  - git commit -m "xingbuxinga"
  - git push --force --quiet "https://${test_token}@${GH_REF}" master:${P_BRANCH}
 branches:
  only:
    - master
